### PR TITLE
Adjust BON earnings

### PR DESCRIPTION
**Pull request by Audionut**
Modify the 'legendary' and 'old' torrent BON earnings to minimize abuse, and heavily reduce BON earnings for torrents that don't necessarily need such encouragement to seed.

### CODE REVIEW

**Review by Roardom — CHANGES_REQUESTED** [review]
We don't plan on committing changes directly to the repo. Instead, we plan on keeping an out of tree patchset which we're still working out the details of.

Also, this is only the front-end. You also have to change https://github.com/EkoNesLeg/UNIT3D-Cinematik-Edition/blob/master/app/Console/Commands/AutoBonAllocation.php

**Comment by Audionut** [comment]
Ta, I didn't read far enough. Also I missed this earlier https://github.com/EkoNesLeg/UNIT3D-Cinematik-Edition/blob/268f864413859037cc39782bfdfa42020f873467/app/Http/Controllers/User/EarningController.php#L138

Does that need changing also?

**Comment by Audionut** [comment]
I guess I should stop dicking around in the web and get a proper dev environment running if we're sticking to the logical process of applying patches.

**Comment by Roardom** [comment]
Yes, that would need to be changed as well

**Comment by Roardom** [comment]
Closed and reopened to trigger CI

**Comment by Roardom** [comment]
Hmm, looks like formatting errors have occurred since the fork.

**Comment by Audionut** [comment]
I can remember spaces/tabs being an issue the magiclantern devs always raised back in 2011. Nice to see nothings changed.

**Comment by EkoNesLeg** [comment]
As discussed, this PR should go via upstream.

**Pull request closed without merging**
